#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Arm,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
* This file contains an efficiently written version of the Protobot RobotC code.
* This code is one that contains unnecessarily efficient code, which should not be
* replicated in production.
*
* It makes extensive use of Ternary Operators (https://renegaderobotics.org/ternary-operator-in-robotc/)
*/


task main()
{
	while(true)
	{
		if(vexRT[Btn5U]){
			motor[Intake] = 60;
		} else if(vexRT[Btn5D]){
			motor[Intake] = -60;
		} else{
			motor[Intake] = 0;
		}

		if(vexRT[Btn6U]){
			motor[Arm] = 127;
		} else if(vexRT[Btn6D]){
			motor[Arm] = -40;
		}
		else{
			motor[Arm] = 0;
		}


		motor[LeftDrive] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[RightDrive] = (vexRT[Ch3] - vexRT[Ch4]);
	}
}
