#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Arm,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
* This file contains an efficiently written version of the Protobot RobotC code. It also features a threading-like feature.
* This code is one that contains unnecessarily efficient code, which should not be
* replicated in production.
*
* It makes extensive use of Ternary Operators (https://renegaderobotics.org/ternary-operator-in-robotc/)
*/

task intake()
{
	while(true){
		signed char intakePower = vexRT[Btn5U] ? 60 : 0;
		motor[Intake] = vexRT[Btn5D] ? -60 : intakePower;
	}

}

task arm(){
	while(true){
		signed char armPower = vexRT[Btn6U] ? 127 : 0;
		motor[Arm] = vexRT[Btn6D] ? -40 : armPower;
	}
}
task main()
{
	startTask(intake);
	startTask(arm);
	while(true)
	{
		motor[LeftDrive] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[RightDrive] = (vexRT[Ch3] - vexRT[Ch4]);
	}
}
