#pragma config(Motor,  port2,           Arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           LeftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
* This file contains a graceful version of the Protobot RobotC code.
* This code is an idealistic one that prioritizes convention and failsafes over efficency.
* If you are an advanced user, this would probably be the better one to follow.
* Beginners should look at the EasyC or Protobot-RobotC-Basic.c
*
*/


/**
* Since RobotC does not have built in documentation genertation, comments
* will be formatted in JavaDOC.
*/

/////////////////////////////////////////
//              VARIABLES              //
/////////////////////////////////////////

signed char dtLeftPower = 0;
signed char dtRightPower = 0;
signed char intakePower = 0;
signed char armPower = 0;



/**
* This function handles the arcade drive. It is based on an article by VRC Team 1666, Renegade Robotics
* that can be seen at https://renegaderobotics.org/robotc-chassis-programming/.
*
*/
void arcade(){
	dtLeftPower = (vexRT[Ch3] + vexRT[Ch4]);
	dtRightPower = (vexRT[Ch3] - vexRT[Ch4]);
}

void tank(){
	dtLeftPower = vexRT[Ch2];
	dtRightPower = vexRT[Ch3];
}


void setMotorPowers(){
	motor[LeftDrive] = dtLeftPower;
	motor[RightDrive] = dtRightPower;
}

/**
* This runs the code for every loop.
* When the function returns false, the process can shut down
* The purpose of a boolean is to allow for a graceful shutdown
*
* @return whether the loop should run again
*/
bool loop(){


	arcade();
	//tank();
	setMotorPowers();
	return true;

}
/**
* This code will be run by the Cortex on enable.
* It runs the loop every time, waiting for a graceful shutdown
*/
task main()
{
	bool run = true;
	while(run){
		run = loop();
	}



}
